# Generated by Django 5.0 on 2024-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('upcoming', 'upcoming'), ('running', 'running'), ('paused', 'paused'), ('completed', 'completed')], max_length=200, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
        ),
    ]
