# Generated by Django 5.0 on 2024-03-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_customer_date_created_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
