# Generated by Django 5.0 on 2024-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_alter_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date',
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('disabled', 'disabled'), ('enabled', 'enabled')], default='enabled', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ShowDay',
        ),
    ]
