# Generated by Django 5.0 on 2024-04-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_remove_customer_mobile_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.showday'),
        ),
    ]
