# Generated by Django 5.0 on 2024-04-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_showday_show_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_id', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.customer')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.showday')),
                ('screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.screen')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.show')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_api.showtime')),
            ],
        ),
    ]
