# Generated by Django 5.0 on 2024-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('disabled', 'disabled'), ('finished', 'finished')], default='active', max_length=200, null=True),
        ),
    ]
