# Generated by Django 5.0 on 2024-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_alter_show_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.FloatField(max_length=200),
        ),
    ]
