# Generated by Django 5.0 on 2024-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_show_price_alter_screen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='screen',
        ),
    ]
