# Generated by Django 5.0 on 2024-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0020_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
