# Generated by Django 5.0 on 2024-04-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0021_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
